#! /bin/bash

# loading configurations
. ~/.config/bspwm/panel_config
. ~/.config/bspwm/panel_colors
. ~/.config/bspwm/custom_config

# window manager configuration
bspc config border_width    3
bspc config window_gap      5

bspc config split_ratio         0.50
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true
bspc config normal_frame_opacity 0.0
bspc config focused_frame_opacity 0.1
bspc config focus_follows_pointer true
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config merge_overlapping_monitors true

bspc monitor -d $(echo -e '\uf0ac') $(echo -e '\uf121') $(echo -e '\uf120') $(echo -e '\uf001') $(echo -e '\uf07c') $(echo -e '\uf109') $(echo -e '\uf0c3') $(echo -e '\uf141')

bspc config normal_border_color '#282828'
bspc config focused_border_color '#d5c4a1'
bspc config presel_border_color '#d79921'
bspc config normal_sticky_border_color '#1d2021'
bspc config focused_sticky_border_color '#d5c4a1'
bspc config urgent_border_color '#cc241d'

# preparing rxvt daemon
xrdb ~/.Xresources
urxvtd -q -o -f

# loading the background, the hotkey manager and the top bar
feh --bg-scale "$HOME/.wallpaper/background.png" &
sxhkd -f 100 &
bspwm_panel &

# loading the system tray bar and the application launcher;
# we should wait at least 1 second otherwise the panel will
# overlap the stalonetray bar
sleep 1
stalonetray -bg $STALONE_BACKGROUND \
    --dockapp-mode $STALONE_DOCK_MODE \
    --geometry $STALONE_GEOMETRY \
    --grow-gravity $STALONE_GROW_GRAVITY \
    --icon-gravity $STALONE_GROW_GRAVITY \
    --icon-size $STALONE_ICON_SIZE \
    --kludges $STALONE_KLUDGES &

# autostart applications
bspwm_autostart &
